//
// Created by charl on 11/25/2025.
//

#ifndef UNTITLED_MACROS_H
#define UNTITLED_MACROS_H

#define PREALLOCATION_COUNT 10000
#define RINGBUFFER_COUNT 32
#define MAPPING_NAME "GATEWAY_ENGINE_SHARED_MEMORY"

#endif //UNTITLED_MACROS_H